
FROM rust:1.63.0

WORKDIR /app

# Copy all files from our working environment to our Docker image
COPY . .
#use metadata generated by cargo sqlx prepare -- --lib
ENV SQLX_OFFLINE true
RUN cargo build --release
ENV APP_ENVIRONMENT production
# When `docker run` is executed, launch the binary!
ENTRYPOINT ["./target/release/webtest"]